/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Cube(props) {
  const { nodes, materials } = useGLTF('/Cube.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[1.5, 0, 1.5]} />
    </group>
  );
}

useGLTF.preload('/Cube.gltf');
