/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Lander(props) {
  const degToRad = (deg) => (deg * Math.PI) / 180.0;

  //lattitude xy
  //longitude xz

  const [r, setR] = useState(2);
  const [theta, setTheta] = useState(degToRad(1));
  const [phi, setPhi] = useState(degToRad(23));

  const [latitude, setlatitude] = useState(Math.PI / 2 - theta);
  const [longitude, setlongitude] = useState(phi);

  //green = z
  //orange=y
  //blue=x

  const [x, setX] = useState(r * Math.sin(latitude) * Math.sin(longitude));
  const [y, setY] = useState(r * Math.cos(latitude));
  const [z, setZ] = useState(r * Math.sin(latitude) * Math.cos(longitude));

  const { nodes, materials } = useGLTF('/lander.glb');
  return (
    <group {...props} dispose={null} scale={0.0003} position={[x, y, z]}>
      <mesh geometry={nodes.Apollo_lunar_module.geometry} material={materials['Material.001']} position={[-0.34, 0, 50.59]} />
    </group>
  );
}

useGLTF.preload('/lander.glb');
