/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Sphere(props) {
  const { nodes, materials } = useGLTF('/sphere.glb');

  //lattitude xy
  //longitude xz

  const [latitude, setlatitude] = useState(Math.PI / 6);
  const [longitude, setlongitude] = useState();

  const [x, setX] = useState(2 * Math.cos(latitude));
  const [y, setY] = useState(2 * Math.sin(latitude));
  const [z, setZ] = useState(2 * Math.sin(Math.PI / 6) * 0);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} scale={0.1} position={[x, y, z]} />
    </group>
  );
}

useGLTF.preload('/sphere.glb');
