/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Lander(props) {
  const { lat, long } = props;
  const degToRad = (deg) => (deg * Math.PI) / 180.0;

  const r = 2;

  const { nodes, materials } = useGLTF('/lander.glb');
  return (
    <group
      {...props}
      dispose={null}
      scale={0.0005}
      position={[
        r * Math.sin(Math.PI / 2 - degToRad(lat)) * Math.sin(degToRad(long)),
        r * Math.cos(Math.PI / 2 - degToRad(lat)),
        r * Math.sin(Math.PI / 2 - degToRad(lat)) * Math.cos(degToRad(long)),
      ]}
      rotation={[Math.PI / 2 - degToRad(lat), 0, -degToRad(long)]}
    >
      <mesh geometry={nodes.Apollo_lunar_module.geometry} material={materials['Material.001']} scale={0.5} />
    </group>
  );
}

useGLTF.preload('/lander.glb');
