/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Surface(props) {
  const { nodes, materials } = useGLTF('/surface.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Apollo_17.geometry}
        material={materials['Material.001']}
        scale={0.04}
        position={[0, -0.61, 0]}
        rotation={[0, Math.PI / 2 + Math.PI / 4.66, 0]}
      />
    </group>
  );
}

useGLTF.preload('/surface.glb');
